name: Update Release Branch

on:
  push:
    branches:
      - main

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'
      - name: Set up Git identity
        run: |
          git config --global user.name "Leesa Ward"
          git config --global user.email "leesa@doubleedesign.com.au"
      - name: Delete release branch on remote if it exists
        run: |
          if git show-ref --quiet refs/heads/release; then
            git push origin --delete release
          fi
      - name: Create empty release branch
        run: |
          git checkout --orphan release
          git reset
      - name: Build from main branch
        run: |
          npm install
          npm run build
      - name: Add required files for release
        run: |
          git add gutenberg.php
          git add post-content.php
          git add lib
          git add build -f
          git add packages/block-serialization-default-parser
      - name: Cleanup
        run: |
          git clean -f -d
      - name: Commit and push release branch
        run: |
          git commit -m "Automated update of release branch"
          git push origin release -f

